Feature/#12 implement email confirmation
IliaWizy/education-app pull request #13
Opened 2024-01-14 15:29 UTC by DMCHMB

2024-01-15 18:57 UTC, IliaWizy commented on .github/workflows/workflowForDevelop.yml
> +      - feature/*
лишний пуш на промежуточных, не окончательных действия - это ресурсы. ресурсы стоят денег. иногда одна строка может стоить миллионы. пуш на ветку фичи, чтобы собирать артифакт? где его потом используют, что такая потребность?

2024-01-15 19:00 UTC, IliaWizy commented on config/checkstyle/checkstyle.xml
> +<!--        <module name="AvoidStarImport"/>-->
https://checkstyle.sourceforge.io/checks/imports/avoidstarimport.html или донастроить для библиоткет или оставить. но для использования импорта всего пакета - нет.

2024-01-15 19:02 UTC, IliaWizy commented on http/register_user_duplicate.http
как пишешь unit тест? один класс - один класс теста. тут почем N файлов для теста?

2024-01-15 19:05 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/AppStarter.java
> -@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
миграцию также можно было отключить. 
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.html

2024-01-15 19:09 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/AuthorizationController.java
> +@RequestMapping("/api/v1")
- /api излишне. обычно они на домене/ поддомене
- AuthorizationController что говорит его имя? контроллер авторизация, а значит - /v1/... - тк класс название класса должно давать понять что внутри него и группировать методы контроллера

2024-01-15 19:10 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/AuthorizationController.java
> +  @PostMapping("/auth/sign-up")
см выше. оставляем?

2024-01-15 19:10 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/AuthorizationController.java
> +  @GetMapping("/activation")
см выше. оставляем?

2024-01-15 19:10 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/AuthorizationController.java
> +    return "{\"message\": \"Email confirmation message has been sent\"}";
обсуждали это. исправляем

2024-01-15 19:11 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/AuthorizationController.java
> +}
исправляем по обсуждению вчера

2024-01-15 19:12 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/controller/GlobalExceptionHandler.java
> +@Order(Ordered.HIGHEST_PRECEDENCE)
если тут глобальный, значит есть не глобальный, раз появился приоритет!? если глобальным выставить наивысший, то при равнозначном исключении у глобального будет приоритет. мы этого точно хотим? или название класса несет иной смысл?

2024-01-15 19:14 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/dto/UserDto.java
> +  @NotNull(message = "Email must not be null", groups = OnCreate.class)
нот блан разве не включает параметр этой аннотации? почитай внутри нот нал и нот бланк.

2024-01-15 19:15 UTC, IliaWizy commented on src/main/resources/application.yml
> +      ddl-auto: none
?

2024-01-15 19:16 UTC, IliaWizy commented on src/main/resources/liquibase/changesets/001-create-users-table-tokens-table.sql
- на 2
- иф нот экзист

2024-01-15 19:17 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/VerificationToken.java
> +  @OneToOne(cascade = {
вопрос был открыт. оставляешь?

2024-01-15 19:17 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/VerificationToken.java
> +  private int id;
лонг

2024-01-15 19:19 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/VerificationToken.java
> +  private String token;
добавь uuid. в миграцию соответственно тоже, если потребуется. если на текущем этапе это долго и есть вопросы - запиши этот пункт в таску.

2024-01-15 19:23 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/User.java
> +  private boolean isActive;
+ правим поле

2024-01-15 19:24 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/User.java
> +@Data
нет

2024-01-15 19:27 UTC, IliaWizy commented on src/main/resources/liquibase/changesets/001-create-users-table-tokens-table.sql
> +    FOREIGN KEY (user_id) REFERENCES users (id)
ограничения точно все указаны? на код бэка не рассчитываем - бд живет своей жизнью

2024-01-15 19:36 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/dto/UserDto.java
> +  private String email;
package jakarta.validation.constraints;
изучи пакет. по возможности - убери валидацию хайбера и замени на джакарту.

2024-01-15 19:37 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/dto/mappers/UserMapper.java
дима давал совет. давай прислушаемся к нему.

2024-01-15 19:44 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailServiceImpl.java
> +      message.setText("http://localhost:8080/api/v1/activation?token=" + token);
если завтра порт изменится или есть что- будем править код?

2024-01-15 19:46 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailServiceImpl.java
так понял, что не дописан. когда досан будет - подумаем - а если сервер который отправляет - будет висеть - мы будем его ждать? как сделать, чтобы не ждать? можем сразу это учесть?

2024-01-15 19:46 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/VerificationTokenService.java
> +  VerificationToken findByToken(String token);
отдаем токен и его же возвращаем?

2024-01-15 19:48 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/UserService.java
> +public interface UserService {
пора уже как-то утвердить - какие методы мы используем. предложи варианты из общеупотребляемых, чтобы на всем проекте прослеживалась одна история методов

2024-01-15 19:59 UTC, IliaWizy commented on build.gradle.kts
mavenLocal() первым

2024-01-15 20:11 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/UserServiceImpl.java
> +    return userRepository.findById(id).get();
плохая практика. стрим апи изучаем!!! или бозово пишем, чтобы дважды не дергать репозиторий.

как вариант:
`return userRepository
            .findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("User doesn't exists"));`

2024-01-15 20:15 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/UserServiceImpl.java
> +    return userRepository.findById(id).get();
остальные посмотри с учетом всех пометок и что вчера обсуждали.

2024-01-15 20:15 UTC, IliaWizy requested changes
внеси правки

2024-01-16 13:20 UTC, sursindmitry commented on config/checkstyle/checkstyle.xml
> +<!--        <module name="AvoidStarImport"/>-->
А не проще оставить Гугловский чекстайл и сделать, что бы IDE не делала эти звёздочки?
![image](https://github.com/IliaWizy/education-app/assets/40328886/1cf1b89b-d327-47a2-b26c-8116b78be9be)

2024-01-16 16:29 UTC, IliaWizy commented on config/checkstyle/checkstyle.xml
> +<!--        <module name="AvoidStarImport"/>-->
да. отличное решение, чтобы иде не объединяло

2024-01-17 08:46 UTC, IliaWizy commented on src/main/resources/liquibase/changesets/001-create-users-table-tokens-table.sql
> +--changeset yourname:create-users-table-tokens-table
yourname == имя авто в таблице ченджлога

2024-01-17 08:55 UTC, IliaWizy commented on src/main/resources/liquibase/changesets/001-create-users-table-tokens-table.sql
если что-то пойдет не так - нужна инструкция отката
после  всех манипуляций/ действий
--rollback DROP TABLE users;

поэтому в тч нужно отдельно разносить + представь, что нужно соблюдать обратную совместимость между релизами и в новой версии только одна таблица некорректно мигрирует и ее изменения не существенны, чтобы откатывать весь релиз. писать новую миграцию по всему релизу?

если нужно совместить несколько операций, например таблица + индекс + секвенс, то на каждую операцию делается отдельный ченджсет, с инкриментом (порядок выполнения)

пример:
```
--liquibase formatted sql
--add users table

--changeset username:1
CREATE TABLE IF NOT EXISTS users
(
...
);

--changeset гыуктфьу:2
CREATE INDEX indx_user_email ON users(email);

--rollback DROP INDEX indx_user_email;
--rollback DROP TABLE users;
```

2024-01-17 22:31 UTC, DMCHMB commented on config/checkstyle/checkstyle.xml
> +<!--        <module name="AvoidStarImport"/>-->
Спасибо! Я даже занесу себе в заметки

2024-01-18 01:48 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/AppStarter.java
> -@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
Как делаем? Отключаем миграцию, либо делаем как в dev:
exclude = {DataSourceAutoConfiguration.class
?

2024-01-18 01:52 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/model/User.java
> +@Data
прошу помощи, как правильно сделать. Не уверен, что в новом коммите правильно реализовал

2024-01-18 01:52 UTC, DMCHMB commented on src/main/resources/liquibase/changesets/001-create-users-table-tokens-table.sql
> +    FOREIGN KEY (user_id) REFERENCES users (id)
ограничения надо обсудить, задачу решенной не помечаю

2024-01-18 01:54 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/service/impl/EmailServiceImpl.java
записал в таску

2024-01-18 01:55 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/model/VerificationToken.java
> +  private String token;
завел таску #14

2024-01-18 01:55 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/service/VerificationTokenService.java
> +  VerificationToken findByToken(String token);
Возвращает объект, в котором хранятся одновременно токен (строка) и user (объект). Не уверен, что верно реализовал

2024-01-18 01:56 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/service/UserService.java
> +public interface UserService {
Нужно определиться, не закрываю

2024-01-18 02:09 UTC, DMCHMB commented on http/register_user_duplicate.http
не разобрался, как написать тест по активации пользователя (как получить емаил-токен)

2024-01-18 02:12 UTC, DMCHMB commented
#12: Code refactoring:

Added:
ActivationController;
logging capability

Replaced by: 
AuthController -> RegistrationController
VerificationToken -> EmailVerificationToken
VerificationTokenService -> EmailVerificationTokenService
VerificationRepository -> EmailVerificationRepository

Added migrations to the database, added cascading token deletion on user deletion

Implemented layered architecture approach 
(controller->service->repository->service->controller)

Updated readme.md, described actions required to send email to user

2024-01-20 14:54 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/AppStarter.java
> -@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
на откуп тебе. в итоге, как эксперимент, если останется время - попробуй придумать как реализовать миграцию для прода и разработки одновременно. если нет - потом расскажу про этот чит

2024-01-20 14:56 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/model/User.java
> +@Data
убрать дату и оставить гет. сет. что нужно. в чат скидывал статью про дату.

2024-02-03 06:01 UTC, closed without merging