#12: Registration and Activation User
IliaWizy/education-app pull request #16
Opened 2024-01-18 11:44 UTC by sursindmitry

2024-01-18 15:03 UTC, IliaWizy requested changes
в PR есть файлы не относящиеся к нему

2024-01-18 23:17 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/database/entity/EmailVerificationToken.java
> +@Builder
в идеале чтобы эти объекты были имутабельны, а вся бизнес логика была в доменной модели. у нас доменной нет, поэтому или конструктор или билдер.
@DMCHMB @sursindmitry решите плз

2024-01-18 23:20 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/EmailService.java
> +  void sendConfirmationEmail(String email, Context context) throws MessagingException;
отправляется контекст? возможно, метод который будет реализован неверно назван или выполняет другую функцию

2024-01-18 23:22 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/RegistrationFacade.java
> +  ActivationResponse verification(String token);
на первый взгляд кажется лишним или не относится к фасаду

2024-01-18 23:26 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/web/controller/RegistrationController.java
> +      throws MessagingException {
!! -- throws MessagingException

2024-01-18 23:28 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/EmailService.java
> +  void sendConfirmationEmail(String email, Context context) throws MessagingException;
throws MessagingException
с этим контроллер ничего делать не должен, а тб отправлять дальше

2024-01-18 23:29 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/RegistrationService.java
> +  User register(SignUpRequestDto requestDto);
сервис принял dto и и вернул dto, а контроллер его отобразил просящему

2024-01-18 23:36 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/VerificationService.java
> +  User verification(String token);
verification - проверка токена,  судя по сигнатуре метода. а вот контракт метода не понятен. проверили токен и вернули сущность пользователя, в сервисе верификации.
стоит пересмотреть контракт метода или изменить  последовательность от контроллера.

2024-01-18 23:40 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailServiceImpl.java
> +      emailSender.send(message);
контекст - определить и решить откда должен повиться.

судя по телу тут происходит не только отправка сообщения.

2024-01-18 23:49 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailServiceImpl.java
> +      throw new MessagingException();
поймали ок. для чего? чтобы уточнить что конкретно произошло? тогда нужен кастомный эксепшен, например ConfirmationEmailException.
а через AOP или ControllerAdvice->ExceptionHandler обрабатывать. логировать ошибки на уровне обработки, чтобы сосредоточиться в одном месте, а не по всему коду искать где логируем.

2024-01-18 23:53 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailVerificationTokenServiceImpl.java
> +    emailVerificationToken.setExpirationTime(calculateExpiryDate(24));
в одну строку реализуй. билдер для таких вещей и создавался. внутри тело - это излишняя настроечная история, не несущая никакого смысла, чтобы выделять ее.

2024-01-19 00:02 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/EmailVerificationTokenServiceImpl.java
> +    emailVerificationToken.setExpirationTime(calculateExpiryDate(24));
отдельный метод не несет ничего. настройка.
```
Instant.now().plus(Duration.ofHours(24))
```
а вот 24 это нужно вынести в настройки приложения и добавить константу, в которой  через @Value("${что-то из настроек берем}")

2024-01-19 00:07 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/RegistrationFacadeImpl.java
похожие пометки. учесть в этом сервисе.

2024-01-19 00:13 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/service/impl/RegistrationServiceImpl.java
> +    });
общая логика:
1. проверка предусловия
2. логика
3. проверка постусловия
тут получается, что в случае если есть пользователь, то мы заранее создали ресурсы какие то. не критично но все же. + касательно искючений уже есть правка.

2024-01-19 00:16 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/database/entity/User.java
> +  private Set<Role> roles;
смотрится преждевременно, тк ничего не дает без курсов.

2024-01-19 00:20 UTC, IliaWizy commented on src/main/java/com/wizy/educationapp/web/dto/SignUpRequestDto.java
> +    @NotBlank(message = "password must NOT be null or empty")
минимум 6, макс ХХ. используй это в сообщении в виде ссылки на параметр

2024-01-19 00:27 UTC, IliaWizy commented on src/main/resources/liquibase/changesets/db.changelog-1.0.sql
если делаем в одну миграцию. но лучше в 3.
всегда придерживаемся установленной иерархии библиотеки и пишем rollback:

```
--liquibase formatted sql
--add users table

--changeset IliaWizy:1
CREATE TABLE IF NOT EXISTS users
(
  id        BIGSERIAL PRIMARY KEY,
    email     VARCHAR(255) NOT NULL unique,
    firstname VARCHAR(255) NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    active    BOOLEAN
);

--changeset IliaWizy:2
...

--changeset IliaWizy:3
...

--rollback 3;
--rollback 2;
--rollback DROP TABLE users;
```

2024-01-21 20:11 UTC, DMCHMB commented on src/main/java/com/wizy/educationapp/service/RegistrationService.java
> +  User register(SignUpRequestDto requestDto);
Логика преобразования в dto вынесена в фасад.

2024-01-21 21:02 UTC, DMCHMB requested changes
Поменяй плз структуру проекта, как собирались:

- маперы относятся к слою сервисов, не web. они конвертируют слои представления(dto)/ доменной модели(domain) в отображение бд (entity) и порожняк обратно ))
- слоя web нет. можно/ нужно вынести controller и в нем dto. 
- database тоже нет такого слоя. оставляем repository как абстракцию приближенную к сервисному слою и взаимодействию с хранилищем (не путаем с с более низкоуровневой dao), а в нем как раз entity и фактически сами репозитории.

2024-01-22 06:44 UTC, sursindmitry commented
> 1. Поменяй плз структуру проекта, как собирались:
> 

> * маперы относятся к слою сервисов, не web. они конвертируют слои представления(dto)/ доменной модели(domain) в отображение бд (entity) и порожняк обратно ))

 Я бы вообще мапал в entity  в контроллере. и обратно в response.

```
@PostMapping("/register")
public SignUpResponseDto register(@Valid @RequestBody SignUpRequestDto requestDto) {

        User savedUser = signUpMapper.toEntity(requestDto);

        return signUpMapper.toDto(registrationFacade.registeredUserAndSendEmail(savedUser), "Аккаунт создан. Подтвердите почту.");
    }
```

В чём прикол это куда то выносить в другую логику, а потом искать где то в классе `RegistrationServiceImpl`, как там у нас мапится к User - я не понимаю.


> * слоя web нет. можно/ нужно вынести controller и в нем dto.
> * database тоже нет такого слоя. оставляем repository как абстракцию приближенную к сервисному слою и взаимодействию с хранилищем (не путаем с с более низкоуровневой dao), а в нем как раз entity и фактически сами репозитории.

Я думал мы оставляем такую структуру как сейчас. 

> 
> 2. Также надо добавить ручные http тесты в одном файле

Зачем они нужны вообще? Просто показать какие адреса доступны?

> 3. По базе данных:
>    вроде теперь вместо serial рекомендовано писать
>    "generated by default as identity"
> 
> надо установить дополнительные проверки, кроме unique и not null, предлагаю:
> 
> CREATE TABLE IF NOT EXISTS users ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE CHECK (email ~* '^[a-zA-Z0-9_+&-]+(?:.[a-zA-Z0-9_+&-]+)*@(?:[a-zA-Z0-9-]+.)+[a-zA-Z]{2,7}$'), name VARCHAR(255) NOT NULL CHECK (name <> ''), password VARCHAR(255) NOT NULL CHECK (LENGTH(password) BETWEEN 6 AND 20), active BOOLEAN );
> 
> CREATE TABLE IF NOT EXISTS email_verification_token ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token VARCHAR(255), user_id BIGINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION, expiration_time TIMESTAMP );
> 
> regex для почты взял отсюда: https://owasp.org/www-community/OWASP_Validation_Regex_Repository
> 
> С такими проверками теперь любая невалидная информация даст 500 ошибку. Надо ли ее переводить в другой формат?

Зачем мы так усложнять БД? Зачем тогда валидация DTO нужна, если в БД мы можем отсеять всё что нужно? Недоверие к библиотеке jakarta.validation? Ещё и регулярки, я вообще не понимаю как это прочитать... тут прям надо подумать, что бы понять что туда можно положить, а что нет.

2024-01-25 03:18 UTC, DMCHMB approved these changes

2024-02-03 05:57 UTC, merged