#1: Initialize project. Create manual http test
IliaWizy/education-app pull request #4
Opened 2024-01-05 09:54 UTC by DMCHMB

test in folder ./http

2024-01-07 09:00 UTC, sursindmitry approved these changes

2024-01-07 13:33 UTC, DMCHMB commented on build.gradle.kts
> +    testImplementation("org.springframework.boot:spring-boot-starter-test")
test comment

2024-01-07 16:40 UTC, IlyaLisov commented on build.gradle.kts
> +    testImplementation("org.springframework.boot:spring-boot-starter-test")
test comment

2024-01-07 16:44 UTC, IliaWizy requested changes
подход 1

2024-01-07 16:45 UTC, IliaWizy commented on .github/workflows/workflowForDevelop.yml
> +name: Develop branch workflow
saas

2024-01-07 16:46 UTC, IliaWizy commented on .github/workflows/workflowForDevelop.yml
> +
asdsa

2024-01-07 16:47 UTC, IliaWizy commented on build.gradle.kts
> +plugins {
single cooment

2024-01-09 00:28 UTC, IliaWizy approved these changes

2024-01-09 00:28 UTC, merged